import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "en" | "bn";

// ── Full Translation Dictionary ─────────────────────────────────────────────
const TRANSLATIONS = {
  en: {
    // ── Navbar ──────────────────────────────────────────────────────────────
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.library": "Library",
    "nav.donate": "Donate",
    "nav.events": "Events",
    "nav.blog": "Blog",
    "nav.explore": "Explore",
    "nav.inclusive": "Inclusive Education",
    "nav.inclusive.desc": "Accessibility-first learning",
    "nav.gamification": "Gamification",
    "nav.gamification.desc": "Read, earn & compete",
    "nav.volunteer": "Volunteer",
    "nav.volunteer.desc": "Join our global mission",
    "nav.signIn": "Sign In",
    "nav.myLibrary": "My Library Dashboard",
    "nav.signOut": "Sign Out",
    "nav.signInRegister": "Sign In / Register",
    "nav.adminDashboard": "Admin Dashboard",
    "nav.adminLogin": "Admin Login",
    "nav.donateBtn": "Donate",
    "nav.backToSite": "Back to Site",
    "nav.project": "Project",
    "nav.humanLibrary": "Human Library Programme",
    // ── Accessibility ────────────────────────────────────────────────────────
    "access.title": "Accessibility",
    "access.highContrast": "High Contrast",
    "access.largeFonts": "Large Fonts",
    "access.openDyslexic": "OpenDyslexic",
    // ── Footer ───────────────────────────────────────────────────────────────
    "footer.tagline": "Humanity Public Library (HPL) is the first public library in Nalian village, Khulna. It serves as a community learning hub in a climate-vulnerable coastal area, offering education for all.",
    "footer.explore": "Explore",
    "footer.platform": "Platform",
    "footer.contact": "Contact Us",
    "footer.newsletter": "Newsletter",
    "footer.newsletterPlaceholder": "your@email.com",
    "footer.copyright": "© 2026 Humanity Public Library. All rights reserved.",
    "footer.cta.title": "Together, We Build the World's Most",
    "footer.cta.highlight": "Inclusive Library",
    "footer.cta.desc": "Every book donated, every volunteer hour, every share — moves us closer to free knowledge for all.",
    "footer.cta.donate": "Donate Now",
    "footer.cta.volunteer": "Become a Volunteer",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Use",
    "footer.accessibility": "Accessibility",
    "footer.links.library": "Digital Library",
    "footer.links.inclusive": "Inclusive Education",
    "footer.links.gamification": "Gamification",
    "footer.links.volunteer": "Volunteer Programme",
    "footer.links.blog": "Blog & Stories",
    "footer.links.events": "Events",
    "footer.links.donate": "Donate",
    "footer.memberDashboard": "Member Dashboard",
    "footer.adminPanel": "Admin Panel",
    "footer.freeEbooks": "Free eBooks",
    "footer.audiobooks": "Audiobooks",
    "footer.readingStreaks": "Reading Streaks",
    "footer.brailleSupport": "Braille Support",
    "footer.sponsorship": "Sponsorship",
    // ── Home Page ─────────────────────────────────────────────────────────────
    "home.impact.label": "Our Impact",
    "home.impact.title": "Numbers That Tell Our Story",
    "home.stat.booksAvailable": "Books Available",
    "home.stat.audiobooks": "Audiobooks",
    "home.stat.activeReaders": "Active Readers",
    "home.stat.accessibleUsers": "Accessible Users",
    "home.stat.volunteers": "Volunteers",
    "home.stat.bdtDonated": "BDT Donated",
    "home.stat.countries": "Countries Served",
    "home.stat.languages": "Languages",
    "home.featured.label": "Our Collection",
    "home.featured.title": "Featured Books",
    "home.featured.viewAll": "View All Library",
    "home.featured.audio": "Audio",
    "home.featured.available": "Available",
    "home.featured.unavailable": "Borrowed",
    "home.featured.readNow": "Read Now",
    "home.inclusive.badge": "WCAG 2.1 AA Compliant",
    "home.inclusive.title": "Built for Every Human, Not Just Some.",
    "home.inclusive.desc": "Our Inclusive Education Module is our greatest achievement — designed from the ground up for visually impaired readers, learners with dyslexia and users in low-bandwidth environments.",
    "home.inclusive.feature1": "Audio Book System",
    "home.inclusive.feature1.desc": "12,000+ books with AI-narrated audio",
    "home.inclusive.feature2": "Voice Navigation",
    "home.inclusive.feature2.desc": "Hands-free library browsing",
    "home.inclusive.feature3": "OpenDyslexic Font",
    "home.inclusive.feature3.desc": "One-click dyslexia-friendly mode",
    "home.inclusive.feature4": "High Contrast Mode",
    "home.inclusive.feature4.desc": "WCAG 2.1 AA certified contrast ratios",
    "home.inclusive.explore": "Explore Inclusive Mode",
    "home.inclusive.floatStat": "Accessible Users Served",
    "home.testimonials.voices": "Voices",
    "home.testimonials.title": "Stories That Move Us",
    "home.donate.changeLife": "Change a Life",
    "home.donate.today": "Today",
    "home.donate.desc": "Your contribution of just ৳500 can give a visually impaired student access to an entire year of audiobooks.",
    "home.donate.btn": "Donate Now",
    "home.donate.volunteer": "Volunteer Instead",
    "home.partners.label": "Trusted By",
    "home.partners.title": "Supported by World-Class Organizations",
    "home.partners.badge.un": "UN Certified",
    "home.partners.badge.iso": "ISO 9001",
    "home.partners.badge.wcag": "WCAG 2.1 AA",
    "home.newsletter.label": "Stay Updated",
    "home.newsletter.title": "Join 48,000+ Readers in Our Community",
    "home.newsletter.desc": "Get weekly book recommendations, impact reports and platform updates delivered to your inbox.",
    "home.newsletter.placeholder": "Enter your email",
    "home.newsletter.btn": "Subscribe Free",
    "home.newsletter.noSpam": "No spam, ever. Unsubscribe anytime.",
    // ── Mission Section ──────────────────────────────────────────────────────
    "mission.label": "SURVIVING THE TIDE",
    "mission.title": "From Devastation to Empowerment",
    "mission.p1": "Since the Bhola Cyclone (1970) and storms like Cyclone Sidr (2007), Cyclone Aila (2009), Cyclone Amphan (2020), and Cyclone Mocha (2023), our coastal communities in Khulna have faced repeated devastation.",
    "mission.p2": "Thousands of homes lost, rivers eroded, and over 50,000 people forced to migrate—yet hope survives through education.",
    "mission.p3": "Support Humanity Public Library today—help children learn, women earn, and communities rebuild stronger against climate disasters.",
    "mission.btn.support": "Support Our Mission",
    "mission.btn.volunteer": "Join as Volunteer",
    "mission.migrants": "Forced Migrants",
    // ── Library ───────────────────────────────────────────────────────────────
    "lib.title": "Digital Library",
    "lib.subtitle": "Explore our collection of",
    "lib.subtitle2": "free books & resources",
    "lib.search": "Search books, authors, genres...",
    "lib.genre": "Genre",
    "lib.language": "Language",
    "lib.filter.all": "All",
    "lib.filter.available": "Available",
    "lib.filter.audio": "Audio Only",
    "lib.filter.saved": "Saved",
    "lib.grid": "Grid",
    "lib.list": "List",
    "lib.noResults": "No books found",
    "lib.noResults.desc": "Try adjusting your search or filters.",
    "lib.borrow": "Borrow",
    "lib.borrowNow": "Borrow Now",
    "lib.borrowDays": "How many days do you need?",
    "lib.returnDate": "Expected return date:",
    "lib.confirmBorrow": "Confirm Borrow Request",
    "lib.loginToBorrow": "Sign in to borrow books",
    "lib.available": "Available",
    "lib.unavailable": "Checked Out",
    "lib.pending": "Pending",
    "lib.audio": "Audio",
    "lib.braille": "Braille",
    "lib.cancel": "Cancel",
    "lib.confirm": "Submit Request",
    "lib.readMore": "View Details",
    "lib.days": "days",
    "lib.yourBorrow": "Your Request",
    "lib.takenByOther": "Taken",
    "lib.alreadyBorrowed": "You have already requested or borrowed this book.",
    // ── Donate ────────────────────────────────────────────────────────────────
    "donate.title": "Make a Difference",
    "donate.subtitle": "Support free education for thousands of learners across Bangladesh and beyond.",
    "donate.tiers.label": "Choose Your Support Level",
    "donate.monthly": "Monthly",
    "donate.oneTime": "One-time",
    "donate.donateAs": "Donating as",
    "donate.yourName": "Your full name",
    "donate.yourMessage": "Leave a message (optional)",
    "donate.proceed": "Proceed to Payment",
    "donate.payWith": "Pay with",
    "donate.sendMoney": "Send money to this number",
    "donate.copyNumber": "Copy Number",
    "donate.copied": "Copied!",
    "donate.enterPhone": "Your sender phone number",
    "donate.enterTxn": "Transaction ID from",
    "donate.verify": "Submit for Verification",
    "donate.verifying": "Verifying...",
    "donate.success": "Thank you for your donation!",
    "donate.successDesc": "Your payment is under review. We'll notify you shortly.",
    "donate.impact.title": "Your Impact",
    "donate.loginRequired": "Please sign in to donate.",
    "donate.loginBtn": "Sign In",
    "donate.step1": "Choose Method",
    "donate.step2": "Send Payment",
    "donate.step3": "Confirm",
    "donate.prevBtn": "Previous",
    "donate.nextBtn": "Next",
    "donate.selectMethod": "Select payment method",
    "donate.merchantNumber": "Merchant Number",
    "donate.totalAmount": "Total Amount:",
    "donate.donateAnother": "Donate Again",
    // ── Volunteer ─────────────────────────────────────────────────────────────
    "vol.label": "Join Our Mission",
    "vol.title": "🤝 Volunteer Platform",
    "vol.subtitle": "Join thousands of passionate volunteers making education accessible worldwide.",
    "vol.name": "Full Name *",
    "vol.email": "Email Address *",
    "vol.phone": "Phone Number",
    "vol.role": "Preferred Role *",
    "vol.experience": "Your Experience & Skills",
    "vol.motivation": "Why do you want to volunteer?",
    "vol.submit": "Submit Application",
    "vol.submitting": "Submitting...",
    "vol.success.title": "Application Submitted! 🎉",
    "vol.success.desc": "Thank you for applying! Our team will review your application and contact you within 3-5 business days.",
    "vol.success.btn": "Apply for Another Role",
    "vol.benefits.title": "Why Volunteer With Us?",
    "vol.alreadyApplied": "You've already applied for this role.",
    "vol.chooseRole": "Choose a Role to Apply",
    "vol.volunteers": "Volunteers",
    "vol.openings": "openings",
    // ── UserAuth ──────────────────────────────────────────────────────────────
    "auth.welcome": "Welcome back",
    "auth.welcomeSub": "Sign in to your HPL account",
    "auth.welcomeNew": "Create your account",
    "auth.welcomeNewSub": "Join the Humanity Public Library community",
    "auth.email": "Email Address",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.name": "Full Name",
    "auth.phone": "Phone Number",
    "auth.studentId": "Student ID (optional)",
    "auth.showPass": "Show",
    "auth.hidePass": "Hide",
    "auth.forgotPassword": "Forgot password?",
    "auth.login": "Log in",
    "auth.register": "Register",
    "auth.loginBtn": "Sign In",
    "auth.registerBtn": "Create Account",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.switchRegister": "Create one",
    "auth.switchLogin": "Sign in",
    "auth.loginSuccess": "Welcome back! Redirecting...",
    "auth.registerSuccess": "Account created! Signing you in...",
    "auth.fillAllFields": "Please fill in all fields.",
    "auth.fillAllRequired": "Please fill in all required fields.",
    "auth.invalidPhone": "Please enter a valid Bangladeshi phone number.",
    "auth.shortPassword": "Password must be at least 6 characters.",
    "auth.passwordMismatch": "Passwords do not match.",
    "auth.emailExists": "An account with this email already exists.",
    "auth.invalidCredentials": "Invalid email or password.",
    "auth.namePlaceholder": "Your full name",
    "auth.emailPlaceholder": "you@example.com",
    "auth.phonePlaceholder": "01XXXXXXXXX",
    "auth.studentIdPlaceholder": "STU001 or NID",
    "auth.passwordPlaceholder": "Min 6 characters",
    "auth.confirmPlaceholder": "Re-enter password",
    // ── Dashboard ─────────────────────────────────────────────────────────────
    "dash.myLibrary": "My Library",
    "dash.welcome": "Welcome,",
    "dash.myBooks": "My Books",
    "dash.history": "History",
    "dash.payments": "Payments",
    "dash.profile": "Profile",
    "dash.editProfile": "Edit Profile",
    "dash.active": "Active",
    "dash.borrowed": "Borrowed",
    "dash.noActiveBooks": "You have no active borrows yet.",
    "dash.browseLibrary": "Browse Library",
    "dash.noHistory": "No borrowing history yet.",
    "dash.noPayments": "No payments yet.",
    "dash.donateNow": "Donate Now",
    "dash.totalDonated": "Total Donated",
    "dash.pending": "Pending",
    "dash.verified": "Verified",
    "dash.saveChanges": "Save Changes",
    "dash.cancel": "Cancel",
    "dash.signOut": "Sign Out",
    "dash.backToSite": "Back to Site",
    "dash.memberSince": "Member since",
    "dash.borrowingPeriod": "Borrowing period",
    "dash.daysLeft": "days left",
    "dash.daysOverdue": "days overdue",
    "dash.dueToday": "Due today!",
    "dash.awaitingApproval": "Waiting for admin approval...",
    "dash.returnBy": "Return by",
    "dash.requested": "Requested",
    "dash.returned": "Returned:",
    "dash.browseMore": "Browse More Books",
    "dash.myProfile": "My Profile",
    "dash.editMyInfo": "Edit My Information",
    "dash.fullName": "Full Name",
    "dash.email": "Email Address",
    "dash.phone": "Phone Number",
    "dash.studentNid": "Student / NID",
    "dash.memberSinceLabel": "Member Since",
    "dash.booksBorrowedLabel": "Books Borrowed",
    "dash.activeLabel": "Active Borrows",
    "dash.totalDonatedLabel": "Total Donated",
    "dash.changePass": "Change Password (optional)",
    "dash.currentPass": "Current password",
    "dash.newPass": "New password (min 6 chars)",
    "dash.confirmNewPass": "Confirm new password",
    "dash.profileSaved": "Saved!",
    // ── Blog ──────────────────────────────────────────────────────────────────
    "blog.label": "Stories & Insights",
    "blog.title": "Blog & Stories",
    "blog.subtitle": "Impact stories, accessibility insights, community updates and more.",
    "blog.searchPlaceholder": "Search articles...",
    "blog.readMore": "Read More",
    "blog.minRead": "min read",
    "blog.noResults": "No articles found.",
    "blog.featuredBadge": "Featured",
    "blog.latestArticles": "Latest Articles",
    // ── Events ────────────────────────────────────────────────────────────────
    "events.label": "What's Happening",
    "events.title": "📅 Events Calendar",
    "events.subtitle": "Book fairs, reading marathons, author talks and workshops — join us!",
    "events.register": "Register",
    "events.registered": "Registered ✓",
    "events.unregister": "Unregister",
    "events.free": "Free",
    "events.online": "Online",
    "events.filterAll": "All Events",
    "events.featured": "Featured",
    "events.upcoming": "Upcoming Events",
    // ── Gamification ──────────────────────────────────────────────────────────
    "game.label": "Gamification",
    "game.title": "Reading Leaderboard",
    "game.subtitle": "Build streaks, earn badges and compete with readers worldwide.",
    "game.dayStreak": "Day Streak",
    "game.totalPoints": "Total Points",
    "game.globalRank": "Global Rank",
    "game.booksRead": "Books Read",
    "game.leaderboard": "Leaderboard",
    "game.badges": "Badges",
    "game.challenges": "Challenges",
    "game.weekly": "Weekly",
    "game.allTime": "All Time",
    "game.rank": "Rank",
    "game.reader": "Reader",
    "game.country": "Country",
    "game.points": "Points",
    "game.you": "You",
    "game.locked": "Locked",
    "game.earned": "Earned",
    "game.progress": "Progress",
    "game.challengeOf": "Challenge of the",
    "game.week": "Week",
    "game.browseLibrary": "Browse Library",
    "game.myStats": "My Stats",
    // ── Inclusive Education ───────────────────────────────────────────────────
    "incl.label": "Inclusive Education",
    "incl.title": "Learning Without Barriers",
    "incl.subtitle": "Built for every learner, everywhere, regardless of ability or connectivity.",
    "incl.getStarted": "Get Started Free",
    "incl.learnMore": "Learn More",
    "incl.feature.audiobooks": "Accessible Audiobooks",
    "incl.feature.braille": "Braille Materials",
    "incl.feature.dyslexia": "Dyslexia Support",
    "incl.feature.lowBandwidth": "Low-bandwidth Mode",
    "incl.feature.multiLang": "Multi-language Content",
    "incl.feature.screenReader": "Screen Reader Ready",
    // ── Human Library ────────────────────────────────────────────────────────
    "hl.title": "HUMAN LIBRARY PROGRAMME",
    "hl.slogan": "Borrow a person. Hear a real story.",
    "hl.desc": "A project of Humanity Public Library, Nalian — where coastal voices become living books. Meet climate migrants, fishers, artisans, and survivors from Bangladesh's most vulnerable shorelines.",
    "hl.livingBooks": "OUR LIVING BOOKS",
    "hl.sessions": "SESSION TYPES",
    "hl.upcoming": "UPCOMING SESSIONS",
    "hl.bookSession": "BOOK A SESSION",
    "hl.shareStory": "Share your story. Become a book.",
    "hl.shareStoryDesc": "If you live in Dacope or the coastal area and have a story worth telling, we want to publish you.",
    "hl.applyBook": "Apply as a book",
    "hl.bookingForm": "Session booking form",
    "hl.yourName": "Your name",
    "hl.emailPhone": "Email or phone",
    "hl.whichBook": "Which book would you like to meet?",
    "hl.sessionType": "Session type",
    "hl.preferredDate": "Preferred date",
    "hl.purpose": "Your purpose (research / awareness / learning / other)",
    "hl.requestSession": "Request session",
    "hl.inPerson": "In-person",
    "hl.inPersonDesc": "Visit Nalian library. Sit with your chosen book. 30–45 min.",
    "hl.online": "Online",
    "hl.onlineDesc": "Join via Zoom or Google Meet from anywhere in the world.",
    "hl.fieldVisit": "Field visit",
    "hl.fieldVisitDesc": "Researchers & journalists — visit the coastal community directly.",
    "hl.groupSession": "Group session",
    "hl.groupSessionDesc": "For schools, NGOs, or teams. Multiple books at once.",
  },

  bn: {
    // ── Navbar ──────────────────────────────────────────────────────────────
    "nav.home": "হোম",
    "nav.about": "আমাদের সম্পর্কে",
    "nav.library": "গ্রন্থাগার",
    "nav.donate": "দান করুন",
    "nav.events": "ইভেন্টস",
    "nav.blog": "ব্লগ",
    "nav.explore": "অন্বেষণ",
    "nav.inclusive": "অন্তর্ভুক্তিমূলক শিক্ষা",
    "nav.inclusive.desc": "সবার জন্য প্রবেশযোগ্য শিক্ষা",
    "nav.gamification": "গেমিফিকেশন",
    "nav.gamification.desc": "পড়ুন, উপার্জন করুন ও প্রতিযোগিতা করুন",
    "nav.volunteer": "স্বেচ্ছাসেবক",
    "nav.volunteer.desc": "আমাদের বৈশ্বিক মিশনে যোগ দিন",
    "nav.signIn": "সাইন ইন",
    "nav.myLibrary": "আমার লাইব্রেরি ড্যাশবোর্ড",
    "nav.signOut": "সাইন আউট",
    "nav.signInRegister": "সাইন ইন / নিবন্ধন",
    "nav.adminDashboard": "অ্যাডমিন ড্যাশবোর্ড",
    "nav.adminLogin": "অ্যাডমিন লগইন",
    "nav.donateBtn": "দান করুন",
    "nav.backToSite": "সাইটে ফিরুন",
    "nav.project": "প্রকল্প",
    "nav.humanLibrary": "হিউম্যান লাইব্রেরি প্রোগ্রাম",
    // ── Accessibility ────────────────────────────────────────────────────────
    "access.title": "অ্যাক্সেসিবিলিটি",
    "access.highContrast": "উচ্চ কন্ট্রাস্ট",
    "access.largeFonts": "বড় ফন্ট",
    "access.openDyslexic": "ওপেন ডিসলেক্সিক",
    // ── Footer ───────────────────────────────────────────────────────────────
    "footer.tagline": "হিউম্যানিটি পাবলিক লাইব্রেরি (এইচপিএল) খুলনার নলিয়ান গ্রামের প্রথম পাবলিক লাইব্রেরি। এটি জলবায়ু-ঝুঁকিপূর্ণ উপকূলীয় অঞ্চলে একটি শিক্ষা ও ক্ষমতায়ন কেন্দ্র হিসেবে কাজ করে।",
    "footer.explore": "অন্বেষণ করুন",
    "footer.platform": "প্ল্যাটফর্ম",
    "footer.contact": "যোগাযোগ করুন",
    "footer.newsletter": "নিউজলেটার",
    "footer.newsletterPlaceholder": "আপনার@ইমেইল.com",
    "footer.copyright": "© ২০২৬ হিউম্যানিটি পাবলিক লাইব্রেরি। সর্বস্বত্ব সংরক্ষিত।",
    "footer.cta.title": "একসাথে আমরা গড়ে তুলছি বিশ্বের সবচেয়ে",
    "footer.cta.highlight": "অন্তর্ভুক্তিমূলক লাইব্রেরি",
    "footer.cta.desc": "প্রতিটি দান, প্রতিটি স্বেচ্ছাসেবী ঘন্টা — আমাদের সবার জন্য বিনামূল্যে জ্ঞানের দিকে এগিয়ে নিয়ে যায়।",
    "footer.cta.donate": "এখনই দান করুন",
    "footer.cta.volunteer": "স্বেচ্ছাসেবক হন",
    "footer.privacy": "গোপনীয়তা নীতি",
    "footer.terms": "ব্যবহারের শর্তাবলী",
    "footer.accessibility": "অ্যাক্সেসিবিলিটি",
    "footer.links.library": "ডিজিটাল গ্রন্থাগার",
    "footer.links.inclusive": "অন্তর্ভুক্তিমূলক শিক্ষা",
    "footer.links.gamification": "গেমিফিকেশন",
    "footer.links.volunteer": "স্বেচ্ছাসেবক কর্মসূচি",
    "footer.links.blog": "ব্লগ ও গল্প",
    "footer.links.events": "ইভেন্টস",
    "footer.links.donate": "দান করুন",
    "footer.memberDashboard": "সদস্য ড্যাশবোর্ড",
    "footer.adminPanel": "অ্যাডমিন প্যানেল",
    "footer.freeEbooks": "বিনামূল্যে ই-বুক",
    "footer.audiobooks": "অডিওবুক",
    "footer.readingStreaks": "পড়ার ধারা",
    "footer.brailleSupport": "ব্রেইল সহায়তা",
    "footer.sponsorship": "স্পনসরশিপ",
    // ── Home Page ─────────────────────────────────────────────────────────────
    "home.impact.label": "আমাদের প্রভাব",
    "home.impact.title": "সংখ্যা যা আমাদের গল্প বলে",
    "home.stat.booksAvailable": "বই পাওয়া যাচ্ছে",
    "home.stat.audiobooks": "অডিওবুক",
    "home.stat.activeReaders": "সক্রিয় পাঠক",
    "home.stat.accessibleUsers": "অ্যাক্সেসযোগ্য ব্যবহারকারী",
    "home.stat.volunteers": "স্বেচ্ছাসেবক",
    "home.stat.bdtDonated": "টাকা দান হয়েছে",
    "home.stat.countries": "দেশ সেবিত",
    "home.stat.languages": "ভাষা",
    "home.featured.label": "আমাদের সংগ্রহ",
    "home.featured.title": "বৈশিষ্ট্যযুক্ত বই",
    "home.featured.viewAll": "সমস্ত লাইব্রেরি দেখুন",
    "home.featured.audio": "অডিও",
    "home.featured.available": "পাওয়া যাচ্ছে",
    "home.featured.unavailable": "ধার নেওয়া হয়েছে",
    "home.featured.readNow": "এখনই পড়ুন",
    "home.inclusive.badge": "WCAG 2.1 AA অনুগত",
    "home.inclusive.title": "প্রতিটি মানুষের জন্য তৈরি, শুধু কিছুর জন্য নয়।",
    "home.inclusive.desc": "আমাদের অন্তর্ভুক্তিমূলক শিক্ষা মডিউল আমাদের সেরা অর্জন — দৃষ্টিপ্রতিবন্ধী পাঠক, ডিসলেক্সিয়া শিক্ষার্থী এবং কম-ব্যান্ডউইথ পরিবেশের ব্যবহারকারীদের জন্য তৈরি।",
    "home.inclusive.feature1": "অডিও বুক সিস্টেম",
    "home.inclusive.feature1.desc": "এআই-বর্ণিত অডিও সহ ১২,০০০+ বই",
    "home.inclusive.feature2": "ভয়েস নেভিগেশন",
    "home.inclusive.feature2.desc": "হাতমুক্ত লাইব্রেরি ব্রাউজিং",
    "home.inclusive.feature3": "ওপেন ডিসলেক্সিক ফন্ট",
    "home.inclusive.feature3.desc": "এক-ক্লিকে ডিসলেক্সিয়া-বান্ধব মোড",
    "home.inclusive.feature4": "হাই কন্ট্রাস্ট মোড",
    "home.inclusive.feature4.desc": "WCAG 2.1 AA প্রত্যয়িত কন্ট্রাস্ট অনুপাত",
    "home.inclusive.explore": "অন্তর্ভুক্তি মোড অন্বেষণ করুন",
    "home.inclusive.floatStat": "অ্যাক্সেসযোগ্য ব্যবহারকারী সেবিত",
    "home.testimonials.voices": "কণ্ঠস্বর",
    "home.testimonials.title": "যে গল্পগুলো আমাদের অনুপ্রাণিত করে",
    "home.donate.changeLife": "একটি জীবন বদলে দিন",
    "home.donate.today": "আজই",
    "home.donate.desc": "মাত্র ৳৫০০ দিয়ে একজন দৃষ্টিপ্রতিবন্ধী শিক্ষার্থীকে সারা বছরের অডিওবুক অ্যাক্সেস দিতে পারেন।",
    "home.donate.btn": "এখনই দান করুন",
    "home.donate.volunteer": "স্বেচ্ছাসেবক হিসেবে যোগ দিন",
    "home.partners.label": "বিশ্বস্ত অংশীদার",
    "home.partners.title": "বিশ্বমানের সংস্থাগুলো দ্বারা সমর্থিত",
    "home.partners.badge.un": "ইউএন সার্টিফাইড",
    "home.partners.badge.iso": "আইএসও ৯০০১",
    "home.partners.badge.wcag": "ডাব্লুসিএজি ২.১ এএ",
    "home.newsletter.label": "আপডেট থাকুন",
    "home.newsletter.title": "আমাদের ৪৮,০০০+ পাঠকের সম্প্রদায়ে যোগ দিন",
    "home.newsletter.desc": "সাপ্তাহিক বই সুপারিশ, প্রভাব প্রতিবেদন এবং প্ল্যাটফর্ম আপডেট পান।",
    "home.newsletter.placeholder": "আপনার ইমেইল লিখুন",
    "home.newsletter.btn": "বিনামূল্যে সাবস্ক্রাইব করুন",
    "home.newsletter.noSpam": "স্প্যাম নেই। যেকোনো সময় আনসাবস্ক্রাইব করুন।",
    // ── Mission Section ──────────────────────────────────────────────────────
    "mission.label": "জোয়ারের বিরুদ্ধে টিকে থাকা",
    "mission.title": "বিপর্যয় থেকে ক্ষমতায়ন",
    "mission.p1": "১৯৭০ সালের ভোলা ঘূর্ণিঝড় এবং সিডর (২০০৭), আইলা (২০০৯), আম্পান (২০২০), ও মোখা (২০২৩) এর মতো ঝড়ের পর থেকে খুলনার উপকূলীয় এলাকা বারবার বিপর্যয়ের মুখে পড়েছে।",
    "mission.p2": "হাজার হাজার ঘরবাড়ি ধ্বংস হয়েছে, নদী ভাঙন হয়েছে এবং ৫০,০০০-এরও বেশি মানুষ বাস্তুচ্যুত হয়েছে—তবুও শিক্ষার মাধ্যমে আশা টিকে আছে।",
    "mission.p3": "আজই হিউম্যানিটি পাবলিক লাইব্রেরিকে সমর্থন করুন—শিশুদের শিখতে, নারীদের উপার্জন করতে এবং জলবায়ু বিপর্যয়ের বিরুদ্ধে শক্তিশালীভাবে গড়ে উঠতে সাহায্য করুন।",
    "mission.btn.support": "আমাদের মিশনে সমর্থন দিন",
    "mission.btn.volunteer": "স্বেচ্ছাসেবক হিসেবে যোগ দিন",
    "mission.migrants": "বাস্তুচ্যুত মানুষ",
    // ── Library ───────────────────────────────────────────────────────────────
    "lib.title": "ডিজিটাল গ্রন্থাগার",
    "lib.subtitle": "আমাদের সংগ্রহ অন্বে���ণ করুন",
    "lib.subtitle2": "বিনামূল্যে বই ও রিসোর্স",
    "lib.search": "বই, লেখক, ঘরানা খুঁজুন...",
    "lib.genre": "ঘরানা",
    "lib.language": "ভাষা",
    "lib.filter.all": "সব",
    "lib.filter.available": "পাওয়া যাচ্ছে",
    "lib.filter.audio": "শুধু অডিও",
    "lib.filter.saved": "সংরক্ষিত",
    "lib.grid": "গ্রিড",
    "lib.list": "তালিকা",
    "lib.noResults": "কোনো বই পাওয়া যায়নি",
    "lib.noResults.desc": "আপনার অনুসন্ধান বা ফিল্টার পরিবর্তন করে দেখুন।",
    "lib.borrow": "ধার নিন",
    "lib.borrowNow": "এখনই ধার নিন",
    "lib.borrowDays": "আপনার কতদিন প্রয়োজন?",
    "lib.returnDate": "প্রত্যাশিত ফেরত তারিখ:",
    "lib.confirmBorrow": "ধার অনুরোধ নিশ্চিত করুন",
    "lib.loginToBorrow": "বই ধার নিতে সাইন ইন করুন",
    "lib.available": "পাওয়া যাচ্ছে",
    "lib.unavailable": "বর্তমানে নেই",
    "lib.pending": "অপেক্ষমাণ",
    "lib.audio": "অডিও",
    "lib.braille": "ব্রেইল",
    "lib.cancel": "বাতিল",
    "lib.confirm": "অনুরোধ জমা দিন",
    "lib.readMore": "বিস্তারিত দেখুন",
    "lib.days": "দিন",
    "lib.yourBorrow": "আপনার অনুরোধ",
    "lib.takenByOther": "নেওয়া হয়েছে",
    "lib.alreadyBorrowed": "আপনি ইতিমধ্যে এই বইটি ধার বা অনুরোধ করেছেন।",
    // ── Donate ────────────────────────────────────────────────────────────────
    "donate.title": "পার্থক্য তৈরি করুন",
    "donate.subtitle": "বাংলাদেশ ও তার বাইরের হাজার হাজার শিক্ষার্থীর জন্য বিনামূল্যে শিক্ষা সমর্থন করুন।",
    "donate.tiers.label": "আপনার সহায়তার স্তর বেছে নিন",
    "donate.monthly": "মাসিক",
    "donate.oneTime": "একবার",
    "donate.donateAs": "দান করছেন",
    "donate.yourName": "আপনার পুরো নাম",
    "donate.yourMessage": "একটি বার্তা রেখে যান (ঐচ্ছিক)",
    "donate.proceed": "পেমেন্টে এগিয়ে যান",
    "donate.payWith": "দিয়ে পেমেন্ট করুন",
    "donate.sendMoney": "এই নম্বরে টাকা পাঠান",
    "donate.copyNumber": "নম্বর কপি করুন",
    "donate.copied": "কপি হয়েছে!",
    "donate.enterPhone": "আপনার প্রেরক নম্বর",
    "donate.enterTxn": "থেকে ট্রানজেকশন আইডি",
    "donate.verify": "যাচাইয়ের জন্য জমা দিন",
    "donate.verifying": "যাচাই করা হচ্ছে...",
    "donate.success": "আপনার দানের জন্য ধন্যবাদ!",
    "donate.successDesc": "আপনার পেমেন্ট পর্যালোচনায় আছে। আমরা শীঘ্রই জানাব।",
    "donate.impact.title": "আপনার প্রভাব",
    "donate.loginRequired": "দান করতে সাইন ইন করুন।",
    "donate.loginBtn": "সাইন ইন",
    "donate.step1": "পদ্ধতি বেছে নিন",
    "donate.step2": "পেমেন্ট পাঠান",
    "donate.step3": "নিশ্চিত করুন",
    "donate.prevBtn": "পূর্ববর্তী",
    "donate.nextBtn": "পরবর্তী",
    "donate.selectMethod": "পেমেন্ট পদ্ধতি বেছে নিন",
    "donate.merchantNumber": "মার্চেন্ট নম্বর",
    "donate.totalAmount": "মোট পরিমাণ:",
    "donate.donateAnother": "আবার দান করুন",
    // ── Volunteer ─────────────────────────────────────────────────────────────
    "vol.label": "আমাদের মিশনে যোগ দিন",
    "vol.title": "🤝 স্বেচ্ছাসেবক প্ল্যাটফর্ম",
    "vol.subtitle": "হাজার হাজার স্বেচ্ছাসেবকের সাথে যোগ দিন যারা শিক্ষাকে সবার জন্য অ্যাক্সেসযোগ্য করছেন।",
    "vol.name": "পুরো নাম *",
    "vol.email": "ইমেইল ঠিকানা *",
    "vol.phone": "ফোন নম্বর",
    "vol.role": "পছন্দের ভূমিকা *",
    "vol.experience": "আপনার অভিজ্ঞতা ও দক্ষতা",
    "vol.motivation": "আপনি কেন স্বেচ্ছাসেবক হতে চান?",
    "vol.submit": "আবেদন জমা দিন",
    "vol.submitting": "জমা দেওয়া হচ্ছে...",
    "vol.success.title": "আবেদন জমা হয়েছে! 🎉",
    "vol.success.desc": "আবেদনের জন্য ধন্যবাদ! আমাদের দল ৩-৫ কার্যদিবসের মধ্যে আপনার সাথে যোগাযোগ করবে।",
    "vol.success.btn": "আরেকটি ভূমিকায় আবেদন করুন",
    "vol.benefits.title": "আমাদের সাথে স্বেচ্ছাসেবক হবেন কেন?",
    "vol.alreadyApplied": "আপনি ইতিমধ্যে এই ভূমিকায় আবেদন করেছেন।",
    "vol.chooseRole": "আবেদনের জন্য একটি ভূমিকা বেছে নিন",
    "vol.volunteers": "স্বেচ্ছাসেবক",
    "vol.openings": "পদ খালি",
    // ── UserAuth ──────────────────────────────────────────────────────────────
    "auth.welcome": "স্বাগতম",
    "auth.welcomeSub": "আপনার HPL অ্যাকাউন্টে সাইন ইন করুন",
    "auth.welcomeNew": "আপনার অ্যাকাউন্ট তৈরি করুন",
    "auth.welcomeNewSub": "হিউম্যানিটি পাবলিক লাইব্রেরি সম্প্রদায়ে যোগ দিন",
    "auth.email": "ইমেইল ঠিকানা",
    "auth.password": "পাসওয়ার্ড",
    "auth.confirmPassword": "পাসওয়ার্ড নিশ্চিত করুন",
    "auth.name": "পুরো নাম",
    "auth.phone": "ফোন নম্বর",
    "auth.studentId": "শিক্ষার্থী আইডি (ঐচ্ছিক)",
    "auth.showPass": "দেখুন",
    "auth.hidePass": "লুকান",
    "auth.forgotPassword": "পাসওয়ার্ড ভুলে গেছেন?",
    "auth.login": "লগ ইন",
    "auth.register": "নিবন্ধন",
    "auth.loginBtn": "সাইন ইন করুন",
    "auth.registerBtn": "অ্যাকাউন্ট তৈরি করুন",
    "auth.noAccount": "অ্যাকাউন্ট নেই?",
    "auth.hasAccount": "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    "auth.switchRegister": "তৈরি করুন",
    "auth.switchLogin": "সাইন ইন করুন",
    "auth.loginSuccess": "স্বাগতম! রিডাইরেক্ট হচ্ছে...",
    "auth.registerSuccess": "অ্যাকাউন্ট তৈরি হয়েছে! সাইন ইন করা হচ্ছে...",
    "auth.fillAllFields": "সব ক্ষেত্র পূরণ করুন।",
    "auth.fillAllRequired": "সব প্রয়োজনীয় ক্ষেত্র পূরণ করুন।",
    "auth.invalidPhone": "সঠিক বাংলাদেশি ফোন নম্বর দিন।",
    "auth.shortPassword": "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।",
    "auth.passwordMismatch": "পাসওয়ার্ড মেলেনি।",
    "auth.emailExists": "এই ইমেইলে ইতিমধ্যে একটি অ্যাকাউন্ট আছে।",
    "auth.invalidCredentials": "ইমেইল বা পাসওয়ার্ড ভুল।",
    "auth.namePlaceholder": "আপনার পুরো নাম",
    "auth.emailPlaceholder": "আপনি@উদাহরণ.com",
    "auth.phonePlaceholder": "০১XXXXXXXXX",
    "auth.studentIdPlaceholder": "STU001 বা এনআইডি",
    "auth.passwordPlaceholder": "কমপক্ষে ৬ অক্ষর",
    "auth.confirmPlaceholder": "পাসওয়ার্ড পুনরায় লিখুন",
    // ── Dashboard ─────────────────────────────────────────────────────────────
    "dash.myLibrary": "আমার লাইব্রেরি",
    "dash.welcome": "স্বাগতম,",
    "dash.myBooks": "আমার বই",
    "dash.history": "ইতিহাস",
    "dash.payments": "পেমেন্ট",
    "dash.profile": "প্রোফাইল",
    "dash.editProfile": "প্রোফাইল সম্পাদনা",
    "dash.active": "সক্রিয়",
    "dash.borrowed": "ধার নেওয়া",
    "dash.noActiveBooks": "এখনো কোনো সক্রিয় ধার নেই।",
    "dash.browseLibrary": "গ্রন্থাগার ব্রাউজ করুন",
    "dash.noHistory": "এখনো কোনো ধারের ইতিহাস নেই।",
    "dash.noPayments": "এখনো কোনো পেমেন্ট নেই।",
    "dash.donateNow": "এখনই দান করুন",
    "dash.totalDonated": "মোট দান",
    "dash.pending": "অপেক্ষমাণ",
    "dash.verified": "যাচাই করা হয়েছে",
    "dash.saveChanges": "পরিবর্তন সংরক্ষণ করুন",
    "dash.cancel": "বাতিল",
    "dash.signOut": "সাইন আউট",
    "dash.backToSite": "সাইটে ফিরুন",
    "dash.memberSince": "সদস্যপদ",
    "dash.borrowingPeriod": "ধারের মেয়াদ",
    "dash.daysLeft": "দিন বাকি",
    "dash.daysOverdue": "দিন মেয়াদোত্তীর্ণ",
    "dash.dueToday": "আজই ফেরত দিন!",
    "dash.awaitingApproval": "অ্যাডমিন অনুমোদনের জন্য অপেক্ষা করছে...",
    "dash.returnBy": "ফেরত দিন",
    "dash.requested": "অনুরোধ করা হয়েছিল",
    "dash.returned": "ফেরত দেওয়া হয়েছে:",
    "dash.browseMore": "আরো বই ব্রাউজ করুন",
    "dash.myProfile": "আমার প্রোফাইল",
    "dash.editMyInfo": "আমার তথ্য সম্পাদনা করুন",
    "dash.fullName": "পুরো নাম",
    "dash.email": "ইমেইল ঠিকানা",
    "dash.phone": "ফোন নম্বর",
    "dash.studentNid": "শিক্ষার্থী / এনআইডি",
    "dash.memberSinceLabel": "সদস্যপদের তারিখ",
    "dash.booksBorrowedLabel": "ধার নেওয়া বই",
    "dash.activeLabel": "সক্রিয় ধার",
    "dash.totalDonatedLabel": "মোট দান",
    "dash.changePass": "পাসওয়ার্ড পরিবর্তন (ঐচ্ছিক)",
    "dash.currentPass": "বর্তমান পাসওয়ার্ড",
    "dash.newPass": "নতুন পাসওয়ার্ড (কমপক্ষে ৬ অক্ষর)",
    "dash.confirmNewPass": "নতুন পাসওয়ার্ড নিশ্চিত করুন",
    "dash.profileSaved": "সংরক্ষিত!",
    // ── Blog ──────────────────────────────────────────────────────────────────
    "blog.label": "গল্প ও অন্তর্দৃষ্টি",
    "blog.title": "ব্লগ ও গল্প",
    "blog.subtitle": "প্রভাবের গল্প, অ্যাক্সেসিবিলিটি অন্তর্দৃষ্টি, সম্প্রদায় আপডেট এবং আরও।",
    "blog.searchPlaceholder": "নিবন্ধ খুঁজুন...",
    "blog.readMore": "আরো পড়ুন",
    "blog.minRead": "মিনিট পড়া",
    "blog.noResults": "কোনো নিবন্ধ পাওয়া যায়নি।",
    "blog.featuredBadge": "বৈশিষ্ট্যযুক্ত",
    "blog.latestArticles": "সর্বশেষ নিবন্ধ",
    // ── Events ────────────────────────────────────────────────────────────────
    "events.label": "কী হচ্ছে",
    "events.title": "📅 ইভেন্ট ক্যালেন্ডার",
    "events.subtitle": "বই মেলা, পড়ার ম্যারাথন, লেখক আলোচনা এবং ওয়ার্কশপ — আমাদের সাথে যোগ দিন!",
    "events.register": "নিবন্ধন করুন",
    "events.registered": "নিবন্ধিত ✓",
    "events.unregister": "নিবন্ধন বাতিল",
    "events.free": "বিনামূল্যে",
    "events.online": "অনলাইন",
    "events.filterAll": "সব ইভেন্ট",
    "events.featured": "বৈশিষ্ট্যযুক্ত",
    "events.upcoming": "আসন্ন ইভেন্টস",
    // ── Gamification ──────────────────────────────────────────────────────────
    "game.label": "গেমিফিকেশন",
    "game.title": "পড়ার লিডারবোর্ড",
    "game.subtitle": "ধারা গড়ুন, ব্যাজ অর্জন করুন এবং বিশ্বজুড়ে পাঠকদের সাথে প্রতিযোগিতা করুন।",
    "game.dayStreak": "দিনের ধারা",
    "game.totalPoints": "মোট পয়েন্ট",
    "game.globalRank": "বৈশ্বিক র‍্যাংক",
    "game.booksRead": "পড়া বই",
    "game.leaderboard": "লিডারবোর্ড",
    "game.badges": "ব্যাজ",
    "game.challenges": "চ্যালেঞ্জ",
    "game.weekly": "সাপ্তাহিক",
    "game.allTime": "সর্বকালীন",
    "game.rank": "র‍্যাংক",
    "game.reader": "পাঠক",
    "game.country": "দেশ",
    "game.points": "পয়েন্ট",
    "game.you": "আপনি",
    "game.locked": "লক",
    "game.earned": "অর্জিত",
    "game.progress": "অগ্রগতি",
    "game.challengeOf": "এর চ্যালেঞ্জ",
    "game.week": "সপ্তাহ",
    "game.browseLibrary": "গ্রন্থাগার ব্রাউজ করুন",
    "game.myStats": "আমার পরিসংখ্যান",
    // ── Inclusive Education ───────────────────────────────────────────────────
    "incl.label": "অন্তর্ভুক্তিমূলক শিক্ষা",
    "incl.title": "বাধাহীন শিক্ষা",
    "incl.subtitle": "প্রতিটি শিক্ষার্থীর জন্য, সর্বত্র, সক্ষমতা বা সংযোগ নির্বিশেষে।",
    "incl.getStarted": "বিনামূল্যে শুরু করুন",
    "incl.learnMore": "আরো জানুন",
    "incl.feature.audiobooks": "অ্যাক্সেসযোগ্য অডিওবুক",
    "incl.feature.braille": "ব্রেইল উপকরণ",
    "incl.feature.dyslexia": "ডিসলেক্সিয়া সহায়তা",
    "incl.feature.lowBandwidth": "কম-ব্যান্ডউইথ মোড",
    "incl.feature.multiLang": "বহু-ভাষিক কন্টেন্ট",
    "incl.feature.screenReader": "স্ক্রিন রিডার প্রস্তুত",
    // ── Human Library ────────────────────────────────────────────────────────
    "hl.title": "হিউম্যান লাইব্রেরি প্রোগ্রাম",
    "hl.slogan": "মানুষকে ধার নিন। বাস্তব গল্প শুনুন।",
    "hl.desc": "হিউম্যানিটি পাবলিক লাইব্রেরি, নলিয়ানের একটি প্রকল্প — যেখানে উপকূলীয় কণ্ঠস্বরগুলো জীবন্ত বই হয়ে ওঠে। বাংলাদেশের সবচেয়ে ঝুঁকিপূর্ণ উপকূলীয় এলাকার জলবায়ু অভিবাসী, জেলে, কারিগর এবং বেঁচে থাকাদের সাথে দেখা করুন।",
    "hl.livingBooks": "আমাদের জীবন্ত বইসমূহ",
    "hl.sessions": "সেশনের ধরন",
    "hl.upcoming": "আসন্ন সেশনসমূহ",
    "hl.bookSession": "সেশন বুক করুন",
    "hl.shareStory": "আপনার গল্প শেয়ার করুন। একটি বই হয়ে উঠুন।",
    "hl.shareStoryDesc": "আপনি যদি দাকোপ বা উপকূলীয় এলাকায় বাস করেন এবং আপনার বলার মতো কোনো গল্প থাকে, তবে আমরা আপনাকে প্রকাশ করতে চাই।",
    "hl.applyBook": "বই হিসেবে আবেদন করুন",
    "hl.bookingForm": "সেশন বুকিং ফর্ম",
    "hl.yourName": "আপনার নাম",
    "hl.emailPhone": "ইমেল বা ফোন",
    "hl.whichBook": "আপনি কোন বইটির সাথে দেখা করতে চান?",
    "hl.sessionType": "সেশনের ধরন",
    "hl.preferredDate": "পছন্দের তারিখ",
    "hl.purpose": "আপনার উদ্দেশ্য (গবেষণা / সচেতনতা / শিক্ষা / অন্যান্য)",
    "hl.requestSession": "সেশনের অনুরোধ করুন",
    "hl.inPerson": "সরাসরি",
    "hl.inPersonDesc": "নলিয়ান লাইব্রেরি পরিদর্শন করুন। আপনার পছন্দের বইয়ের সাথে বসুন। ৩০-৪৫ মিনিট।",
    "hl.online": "অনলাইন",
    "hl.onlineDesc": "বিশ্বের যেকোনো প্রান্ত থেকে জুম বা গুগল মিটের মাধ্যমে যোগ দিন।",
    "hl.fieldVisit": "ফিল্ড ভিজিট",
    "hl.fieldVisitDesc": "গবেষক এবং সাংবাদিকদের জন্য — সরাসরি উপকূলীয় সম্প্রদায় পরিদর্শন করুন।",
    "hl.groupSession": "গ্রুপ সেশন",
    "hl.groupSessionDesc": "স্কুল, এনজিও বা টিমের জন্য। একসাথে একাধিক বই।",
  },
} as const;

type TranslationKeys = keyof typeof TRANSLATIONS.en;

// ── Context ──────────────────────────────────────────────────────────────────
interface LangContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: TranslationKeys) => string;
  isBn: boolean;
  bnFont: string;
}

const LangContext = createContext<LangContextType | undefined>(undefined);

const BN_FONT = "'Hind Siliguri', 'Noto Sans Bengali', sans-serif";
const EN_FONT_HEADING = "'Sora', sans-serif";
const EN_FONT_BODY = "'Inter', sans-serif";

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    const stored = localStorage.getItem("hpl_lang");
    return stored === "bn" ? "bn" : "en";
  });

  useEffect(() => {
    localStorage.setItem("hpl_lang", lang);
    // Apply lang attribute to html for CSS targeting
    document.documentElement.setAttribute("lang", lang === "bn" ? "bn" : "en");
    // When Bangla, set the body font to Hind Siliguri for all text elements
    if (lang === "bn") {
      document.documentElement.style.setProperty("--font-body", BN_FONT);
      document.documentElement.style.setProperty("--font-heading", BN_FONT);
    } else {
      document.documentElement.style.setProperty("--font-body", EN_FONT_BODY);
      document.documentElement.style.setProperty("--font-heading", EN_FONT_HEADING);
    }
  }, [lang]);

  const toggleLang = () => setLang(l => l === "en" ? "bn" : "en");

  const t = (key: TranslationKeys): string => {
    return TRANSLATIONS[lang][key] ?? TRANSLATIONS.en[key] ?? key;
  };

  return (
    <LangContext.Provider value={{ lang, toggleLang, t, isBn: lang === "bn", bnFont: BN_FONT }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}